In [1]:
import torch

x = torch.Tensor(2, 3)    # Create an un-initialized Tensor of size 2x3
print(x)                  # Print out the Tensor


tensor([[2.7064e-08, 4.5908e-41, 2.7064e-08],
        [4.5908e-41, 2.6209e-08, 4.5908e-41]])


In [4]:
x = torch.rand(2, 3)    # Initialize with random values
print(x)

tensor([[0.8294, 0.6554, 0.5502],
        [0.5286, 0.8584, 0.7105]])


In [5]:
y = x.view(6)                    # Resize x to size 6
print(y)

tensor([0.8294, 0.6554, 0.5502, 0.5286, 0.8584, 0.7105])


In [6]:
z = x.view(-1, 2)                # Size 3x2
print(z)

tensor([[0.8294, 0.6554],
        [0.5502, 0.5286],
        [0.8584, 0.7105]])


In [23]:
embedings = [[ 0.0000,  0.0000,  0.0000],
         [ 0.1535, -2.0309,  0.9315],
         [ 0.2000,  0.0000,  0.0000],
         [-0.3655,  0.9897,  0.0635]]

In [24]:
import numpy as np
w = np.array([[1,2,0],[1,1,2],[0,2,1]])
w = torch.from_numpy(w)         # Convert a numpy array to a Tensor
print(w)

tensor([[1, 2, 0],
        [1, 1, 2],
        [0, 2, 1]])


In [32]:
t = torch.from_numpy(np.array([embedings[i] for j in w for i in j]))

In [42]:
t

tensor([[ 0.1535, -2.0309,  0.9315],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.1535, -2.0309,  0.9315],
        [ 0.1535, -2.0309,  0.9315],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.1535, -2.0309,  0.9315]], dtype=torch.float64)

In [41]:
t.view((w.shape[0],w.shape[1]*len(embedings[0])))

tensor([[ 0.1535, -2.0309,  0.9315,  0.2000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [ 0.1535, -2.0309,  0.9315,  0.1535, -2.0309,  0.9315,  0.2000,  0.0000,
          0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.2000,  0.0000,  0.0000,  0.1535, -2.0309,
          0.9315]], dtype=torch.float64)

In [68]:
import torch.nn as nn

embedings = nn.Parameter(torch.tensor(np.array([[ 0.0000,  0.0000,  0.0000],
         [ 0.1535, -2.0309,  0.9315],
         [ 0.2000,  0.0000,  0.0000],
         [-0.3655,  0.9897,  0.0635]])))

In [73]:
embedings

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.1535, -2.0309,  0.9315],
        [ 0.2000,  0.0000,  0.0000],
        [-0.3655,  0.9897,  0.0635]], dtype=torch.float64, requires_grad=True)

In [69]:
w

tensor([[1, 2, 0],
        [1, 1, 2],
        [0, 2, 1]])

In [77]:
 a = torch.Tensor(3, 3, 3)

In [87]:
a[0][0] = embedings[w[0][0]]

In [90]:
for i in range(w.shape[0]):
  for j in range(w.shape[1]):
    a[i][j] = embedings[w[i][j]]

In [91]:
a

tensor([[[ 0.1535, -2.0309,  0.9315],
         [ 0.2000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],

        [[ 0.1535, -2.0309,  0.9315],
         [ 0.1535, -2.0309,  0.9315],
         [ 0.2000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.2000,  0.0000,  0.0000],
         [ 0.1535, -2.0309,  0.9315]]], grad_fn=<CopySlices>)

In [71]:
a = [embedings[i] for j in w for i in j]

In [72]:
a

[tensor([ 0.1535, -2.0309,  0.9315], dtype=torch.float64,
        grad_fn=<SelectBackward>),
 tensor([0.2000, 0.0000, 0.0000], dtype=torch.float64, grad_fn=<SelectBackward>),
 tensor([0., 0., 0.], dtype=torch.float64, grad_fn=<SelectBackward>),
 tensor([ 0.1535, -2.0309,  0.9315], dtype=torch.float64,
        grad_fn=<SelectBackward>),
 tensor([ 0.1535, -2.0309,  0.9315], dtype=torch.float64,
        grad_fn=<SelectBackward>),
 tensor([0.2000, 0.0000, 0.0000], dtype=torch.float64, grad_fn=<SelectBackward>),
 tensor([0., 0., 0.], dtype=torch.float64, grad_fn=<SelectBackward>),
 tensor([0.2000, 0.0000, 0.0000], dtype=torch.float64, grad_fn=<SelectBackward>),
 tensor([ 0.1535, -2.0309,  0.9315], dtype=torch.float64,
        grad_fn=<SelectBackward>)]

In [65]:
torch.tensor(a)

tensor([[ 0.1535, -2.0309,  0.9315],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.1535, -2.0309,  0.9315],
        [ 0.1535, -2.0309,  0.9315],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.2000,  0.0000,  0.0000],
        [ 0.1535, -2.0309,  0.9315]], dtype=torch.float64)